//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.20 at 12:38:33 AM EDT 
//


package net.lam.dau.service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.lam.dau.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.lam.dau.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetZeroToSixtyResponse }
     * 
     */
    public GetZeroToSixtyResponse createGetZeroToSixtyResponse() {
        return new GetZeroToSixtyResponse();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link CreateCarRequest }
     * 
     */
    public CreateCarRequest createCreateCarRequest() {
        return new CreateCarRequest();
    }

    /**
     * Create an instance of {@link GetCarsResponse }
     * 
     */
    public GetCarsResponse createGetCarsResponse() {
        return new GetCarsResponse();
    }

    /**
     * Create an instance of {@link Car }
     * 
     */
    public Car createCar() {
        return new Car();
    }

    /**
     * Create an instance of {@link CreateCarResponse }
     * 
     */
    public CreateCarResponse createCreateCarResponse() {
        return new CreateCarResponse();
    }

    /**
     * Create an instance of {@link GetCarsRequest }
     * 
     */
    public GetCarsRequest createGetCarsRequest() {
        return new GetCarsRequest();
    }

    /**
     * Create an instance of {@link StartCarRequest }
     * 
     */
    public StartCarRequest createStartCarRequest() {
        return new StartCarRequest();
    }

    /**
     * Create an instance of {@link StartCarResponse }
     * 
     */
    public StartCarResponse createStartCarResponse() {
        return new StartCarResponse();
    }

    /**
     * Create an instance of {@link GetZeroToSixtyRequest }
     * 
     */
    public GetZeroToSixtyRequest createGetZeroToSixtyRequest() {
        return new GetZeroToSixtyRequest();
    }

}
