//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.20 at 12:38:33 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dau.lam.net/service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.lam.dau.service;
